services:
  Brisum\FBCrawler\Console\CompanyCrawlCommand:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $adsService: '@fb_crawler.ads.service'
    tags:
      - { name: console.command }

  fb_crawler.ads.service:
    class: App\FBCrawler\Utils\AdsService
    arguments:
      $uploadsDir: '%uploads_dir%'
      $uploadsUrl: '%uploads_url%'
