parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        host: '10.0.0.1'
        port: '3306'
        dbname: 'brisum'
        user: 'root'
        password: '123123q'
        server_version: 'mariadb-10.1.26'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # With Symfony 3.3, remove the `resolve:` prefix
        # url: '%env(resolve:DATABASE_URL)%'

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            AppCore:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Entity'
                alias: App
            StorkCoreBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/brisum/stork/core-bundle/src/Entity'
                prefix: 'Brisum\Stork\Bundle\CoreBundle'
                alias: StorkCoreBundle
