fos_user:
    db_driver: orm

    firewall_name: main

    user_class: Brisum\Stork\Bundle\UserBundle\User

    group:
        group_class: Brisum\Stork\Bundle\UserBundle\UserGroup

    from_email:
        address: "developer@dsrv.in"
        sender_name: "developer@dsrv.in"
