security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

#    acl:
#        connection: default

    providers:
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        admin:
#            pattern:            /%admin_area%(.*)
#            context:            user
#            form_login:
#                provider:       stork_employee
#                login_path:     /%admin_area%/login
#                use_forward:    false
#                check_path:     /%admin_area%/login_check
#                failure_path:   null
#            logout:
#                path:           /%admin_area%/logout
#                target:         /%admin_area%/login
#            anonymous:          true

        main:
            anonymous: ~
