sonata_admin:
    security:
        handler: 'sonata.admin.security.handler.role'

        role_admin: ROLE_EMPLOYEE
        role_super_admin: ROLE_EMPLOYEE

    title: 'Stork'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.employee:
                label: 'Сотрудники'
                icon: '<i class="fa fa-id-card-o" aria-hidden="true"></i>'
                items:
                    - stork.sonata_admin.employee
#    templates:
#        layout:    '@AppCore/SonataAdmin/layout.html.twig'
#        edit:      '@AppCore/SonataAdmin/CRUD/edit.html.twig'
#        dashboard: '@AppCore/SonataAdmin/Core/dashboard.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
