framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/src/Core/Resources/translations'
            - '%kernel.project_dir%/vendor/cms-black-stork/core/src/Resources/translations'
        fallbacks:
            - '%locale%'
