parameters:
    ASSETS_VERSION: 20180808

twig:
    paths:
        '%kernel.project_dir%/src/Core/Resources/templates': AppCore
        '%kernel.project_dir%/vendor/brisum/stork/core-bundle/src/Resources/templates': StorkCoreBundle

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        ASSETS_VERSION: '%ASSETS_VERSION%'