parameters:
    ASSETS_VERSION: 20180808

twig:
    paths:
        '%kernel.project_dir%/src/Core/Resources/templates': AppCore

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
    - '@AppCore/Form/fields.html.twig'

    globals:
        ASSETS_VERSION: '%ASSETS_VERSION%'
